name: LeetDown_CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:

  build-macOS-x86_64:
    runs-on: macos-12
    steps:
    - name: envdetails
      run: brew install neofetch && neofetch --off --color_blocks off --stdout
